# Generated by Django 5.0.3 on 2024-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0006_alter_autor_options_alter_endereco_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="planejamento",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
