# Generated by Django 5.0.3 on 2024-04-07 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0008_alter_livro_planejamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anotacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inclusao", models.DateTimeField(auto_now_add=True)),
                ("anotacao", models.TextField()),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="bibm.livro"
                    ),
                ),
            ],
        ),
    ]
