# Generated by Django 5.0.3 on 2024-04-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0010_alter_historico_data_fim_alter_historico_data_ini_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historico",
            name="data_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
