# Generated by Django 5.0.3 on 2024-06-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0011_alter_historico_data_fim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="data_compra",
            field=models.DateField(null=True),
        ),
    ]
