# Generated by Django 5.0.3 on 2024-06-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0012_alter_livro_data_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="classificacao",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="regiao",
            name="regiao",
            field=models.CharField(max_length=65, unique=True, verbose_name="região"),
        ),
    ]
