# Generated by Django 5.0.3 on 2024-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0013_historico_classificacao_alter_regiao_regiao'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('prim_nome', 'ult_nome'), name='autor_unique'),
        ),
    ]
