# Generated by Django 5.0.3 on 2024-07-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0014_autor_autor_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='regiao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bibm.regiao'),
        ),
    ]
