# Generated by Django 5.0.3 on 2024-07-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0015_alter_livro_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibm.livro'),
        ),
    ]
