# Generated by Django 5.0.3 on 2024-07-12 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0016_alter_historico_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='invisivel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historico',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibm.livro'),
        ),
    ]
