# Generated by Django 5.0.3 on 2024-07-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0017_livro_invisivel_alter_historico_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='invisivel',
            new_name='deletado',
        ),
        migrations.AddField(
            model_name='anotacao',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autor',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endereco',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genero',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historico',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regiao',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
