# Generated by Django 5.0.7 on 2024-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0019_alter_autor_regiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('F', 'Ficção'), ('NF', 'Não-Ficção')], default='F', max_length=2),
        ),
    ]
