# Generated by Django 5.0.3 on 2024-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibm', '0020_livro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='presencial',
            field=models.BooleanField(default=True),
        ),
    ]
