# Generated by Django 5.0.3 on 2024-04-05 19:34

import bibm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, validators=[bibm.models.validacao_endereco]
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=300, null=True)),
                ("comentario", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero", models.CharField(max_length=65, unique=True)),
                ("comentario", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Regiao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regiao", models.CharField(max_length=65, unique=True)),
                ("comentario", models.TextField()),
            ],
        ),
    ]
