# Generated by Django 5.0.3 on 2024-04-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0002_alter_endereco_comentario_alter_genero_comentario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=65, unique=True)),
                (
                    "nacionalidade",
                    models.CharField(blank=True, default="", max_length=65, null=True),
                ),
                ("comentario", models.TextField()),
                (
                    "regiao",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bibm.regiao",
                    ),
                ),
            ],
        ),
    ]
