# Generated by Django 5.0.3 on 2024-04-05 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0004_alter_autor_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300, unique=True)),
                ("editora", models.CharField(max_length=300)),
                ("tema", models.CharField(blank=True, max_length=600, null=True)),
                ("lido", models.BooleanField(default=False)),
                ("data_leitura", models.DateField()),
                ("leria_de_novo", models.BooleanField(default=False)),
                (
                    "classificacao",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ]
                    ),
                ),
                ("data_compra", models.DateField()),
                ("comentario", models.TextField()),
                (
                    "autor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bibm.autor",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bibm.endereco",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bibm.genero",
                    ),
                ),
                (
                    "regiao",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="bibm.regiao",
                    ),
                ),
            ],
        ),
    ]
