# Generated by Django 5.0.3 on 2024-04-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0007_alter_livro_planejamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="planejamento",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
