# Generated by Django 5.0.3 on 2024-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibm", "0009_anotacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historico",
            name="data_fim",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historico",
            name="data_ini",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="historico",
            name="terminou",
            field=models.BooleanField(default=False),
        ),
    ]
